steps:
  # Étape 1: Construction de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}'
      - '.'
    id: 'build-image'

  # Étape 2: Push de l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}'
    id: 'push-image'

  # Nouvelle étape 3: Déploiement sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'  # Nom de votre service Cloud Run
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
    id: 'deploy-to-cloud-run'

# Variables substituables
substitutions:
  _REGION: 'europe-west1'  # Région de votre registry
  _REPOSITORY_NAME: 'streamlit'  # Nom de votre repository dans Artifact Registry
  _IMAGE_NAME: 'streamlit-portfolio'  # Nom de votre image
  _TAG: 'v1'  # Tag de l'image
  _SERVICE_NAME: 'flenne-portfolio'  # Ajoutez le nom de votre service Cloud Run ici

# Configuration des images à sauvegarder
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}'

# Timeout global du build (en secondes)
timeout: '1200s'