steps:
  # Build and push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$$LOCATION-docker.pkg.dev/${PROJECT_ID}/$$REPOSITORY/$$IMAGE:$$TAG'
      - '.'
    secretEnv:
      - 'LOCATION'
      - 'REPOSITORY'
      - 'IMAGE'
      - 'TAG'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$$SERVICE_NAME'
      - '--image'
      - '$$LOCATION-docker.pkg.dev/${PROJECT_ID}/$$REPOSITORY/$$IMAGE:$$TAG'
      - '--region'
      - '$$REGION'
      - '--platform'
      - 'managed'
    secretEnv:
      - 'LOCATION'
      - 'REPOSITORY'
      - 'IMAGE'
      - 'TAG'
      - 'SERVICE_NAME'
      - 'REGION'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/LOCATION/versions/latest
      env: 'LOCATION'
    - versionName: projects/$PROJECT_ID/secrets/REPOSITORY/versions/latest
      env: 'REPOSITORY'
    - versionName: projects/$PROJECT_ID/secrets/IMAGE/versions/latest
      env: 'IMAGE'
    - versionName: projects/$PROJECT_ID/secrets/TAG/versions/latest
      env: 'TAG'
    - versionName: projects/$PROJECT_ID/secrets/SERVICE_NAME/versions/latest
      env: 'SERVICE_NAME'
    - versionName: projects/$PROJECT_ID/secrets/REGION/versions/latest
      env: 'REGION'